dast fix.

diff --git a/.github/workflows/dast.yml b/.github/workflows/dast.yml
--- a/.github/workflows/dast.yml
+++ b/.github/workflows/dast.yml
@@ -3,66 +3,75 @@ name: DAST with OWASP ZAP
 on:
   push:
 
+env:
+  IMAGE_NAME: ghcr.io/nus-iss-projects/flight-backend/flightbackend
+  AMADEUS_API_KEY: ${{ secrets.AMADEUS_API_KEY }}
+  AMADEUS_API_SECRET: ${{ secrets.AMADEUS_API_SECRET }}
+  DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
+
 jobs:
-  build_application:
+  setup-build-deploy:
+    name: Setup, Build, and Store Artifact
     runs-on: ubuntu-latest
-    outputs:
-      image_tag: ${{ steps.set_tag.outputs.image_tag }}
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-
+      - uses: actions/checkout@v2
       - name: Set up JDK 17
-        uses: actions/setup-java@v3
+        uses: actions/setup-java@v2
         with:
-          java-version: '17'
-          distribution: 'temurin'
-          cache: maven
+          distribution: 'adopt'
+          java-version: 17
+      - name: Retrieve firebase credentials
+        run: |
+          echo $DATA | base64 -d > app/google-services.json
+          if [ ! -f "app/google-services.json" ]; then
+            echo "Error: Firebase credentials file not found."
+            exit 1
+          fi    
+      - run: mvn clean install --batch-mode --errors --fail-at-end
+      - name: Upload Artifacts
+        uses: actions/upload-artifact@v2
+        with:
+          name: flightsearch-0.0.1-SNAPSHOT.jar
+          path: target/
 
-      - name: Build with Maven
-        run: mvn clean package
-
+  build-docker-image:
+    name: Dockerize and push to GitHub Container Registry
+    needs: setup-build-deploy
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
       - name: Set build date as image tag
         id: set_tag
         run: |
-          echo "image_tag=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
-          echo "::set-output name=image_tag::$(date +'%Y%m%d%H%M%S')"
-
-  build_docker_image:
-    needs: build_application
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-
-      - name: Set up Docker Buildx
+          echo "IMAGE_TAG=$(date +'%Y%m%d%H%M%S')-dast" >> $GITHUB_ENV
+          echo "::set-output name=image_tag::$(date +'%Y%m%d%H%M%S')-dast"
+      - name: Retrieve saved jar
+        uses: actions/download-artifact@v2
+        with:
+          name: flightsearch-0.0.1-SNAPSHOT.jar
+          path: target/
+      - name: Set up Docker Build
         uses: docker/setup-buildx-action@v1
-
-      - name: Login to GitHub Container Registry
-        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
-
       - name: Build and push Docker image
         run: |
-          docker build --tag ${{ env.IMAGE_NAME }}:${{ needs.build_application.outputs.image_tag }} .
-          docker push ${{ env.IMAGE_NAME }}:${{ needs.build_application.outputs.image_tag }}
+          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io --username ${{ github.actor }} --password-stdin
+          docker build --tag ${{ env.IMAGE_NAME }}:${{ steps.set_tag.outputs.image_tag }} .
+          docker push ${{ env.IMAGE_NAME }}:${{ steps.set_tag.outputs.image_tag }}
 
   perform_dast_scan:
-    needs: build_docker_image
+    needs: build-docker-image
     runs-on: ubuntu-latest
     steps:
       - name: Pull Docker image
-        run: docker pull ${{ env.IMAGE_NAME }}:${{ needs.build_docker_image.outputs.image_tag }}
-
+        run: docker pull ${{ env.IMAGE_NAME }}:${{ needs.build-docker-image.outputs.image_tag }}
       - name: Run Docker container
-        run: docker run -d -p 8888:8888 --name myapp ${{ env.IMAGE_NAME }}:${{ needs.build_docker_image.outputs.image_tag }}
-
+        run: docker run -d -p 8888:8888 --name myapp ${{ env.IMAGE_NAME }}:${{ needs.build-docker-image.outputs.image_tag }}
       - name: OWASP ZAP Scan
         uses: zaproxy/action-baseline@v0.6.0
         with:
           target: 'http://localhost:8888'
           docker_name: 'owasp/zap2docker-stable'
           cmd_options: '-t ${TARGET_URL} -r zap_report.html'
-
       - name: Upload ZAP Report
         uses: actions/upload-artifact@v3
         with:
