sast fix.

diff --git a/.github/workflows/sast.yml b/.github/workflows/sast.yml
--- a/.github/workflows/sast.yml
+++ b/.github/workflows/sast.yml
@@ -16,33 +16,22 @@ jobs:
       pull-requests: write
       repository-projects: write
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
       - name: Retrieve firebase credentials
         run: |
-          echo $DATA | base64 -di > app/google-services.json
-          if [ ! -f "app/google-services.json" ]; then
-            echo "Error: Firebase credentials file not found."
-            exit 1
-          fi   
-      - name: Checkout code
-        uses: actions/checkout@v3
-
+            echo $DATA | base64 -di > app/google-services.json
+            if [ ! -f "app/google-services.json" ]; then
+              echo "Error: Firebase credentials file not found."
+              exit 1
+            fi
       - name: Set up JDK 17
         uses: actions/setup-java@v3
         with:
           java-version: '17'
           distribution: 'temurin'
-
-      - name: Cache Maven packages
-        uses: actions/cache@v2
-        with:
-          path: ~/.m2
-          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
-          restore-keys: |
-            ${{ runner.os }}-m2
-
+          cache: maven
       - name: Build with Maven
-        run: mvn clean install --no-transfer-progress
+        run: mvn -B package --file pom.xml
 
       - name: Download DependencyCheck
         run: |
