SAST fix.

diff --git a/.github/workflows/sast.yml b/.github/workflows/sast.yml
--- a/.github/workflows/sast.yml
+++ b/.github/workflows/sast.yml
@@ -3,10 +3,22 @@ name: SAST Check
 on:
   push:
 
+env:
+  AMADEUS_API_KEY: ${{ secrets.AMADEUS_API_KEY }}
+  AMADEUS_API_SECRET: ${{ secrets.AMADEUS_API_SECRET }}
+  DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
+
 jobs:
   dependency-check:
     runs-on: ubuntu-latest
     steps:
+      - name: Retrieve firebase credentials
+        run: |
+          echo $DATA | base64 -di > app/google-services.json
+          if [ ! -f "app/google-services.json" ]; then
+            echo "Error: Firebase credentials file not found."
+            exit 1
+          fi  
       - name: Checkout code
         uses: actions/checkout@v3
 
